image:
  file: .gitpod.Dockerfile

tasks:
  - name: Initialize Terraform
    command: |
      terraform init
      terraform plan && exit 0

vscode:
  extensions:
    - cschleiden.vscode-github-actions
    - hashicorp.terraform
    - ms-azuretools.vscode-docker
    - redhat.vscode-yaml
