image:
  file: .gitpod.Dockerfile

tasks:
  - name: Initialize Terraform
    command: |
      set -o errexit
      set -o xtrace
      terraform init
      terraform plan

vscode:
  extensions:
    - hashicorp.terraform
