image:
  file: .gitpod.Dockerfile

tasks:
  - name: Initialize Terraform
    command: |
      terraform init
      terraform plan

vscode:
  extensions:
    - hashicorp.terraform
    - ms-azuretools.vscode-docker
